### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by jernejbanevec** [tinarazic/BusinessNet#1]
Pozdravljeni,
preletel sem vajin ER diagram in imam naslednje pripombe oziroma vprašanja:
* Entiteti _ZAPOSLENI_ in _KOMENTARJI_ sta tu povezani tako, da ima vsak zaposlen natanko en komentar in vsak komentar vsaj enega zaposlenega (bolj smiselni se zdi, da ima vsak zaposlen poljubno število komentarjev, torej tu ni omejitve, ter da ima vsak komentar natanko enega zaposlenega, ki je ta komentar napisal).
* Ali lahko posamezen zaposleni dela le na enem projektu, kot je označeno na diagramu ali lahko dela na več projektih hkrati?
* Ali se lahko posamezen komentar nanaša na več projektov, kot je tu označeno, ali le na enega?

Sicer se mi zdi pa ER diagram ustrezen.

**Comment by tinarazic** [comment]
Zdravo. 

Z vsemi opazkami se strinjava in sva popravili najin ER diagram.
