### ISSUE TITLE
Zaključek

### ISSUE THREAD

**Issue by tinarazic** [tinarazic/BusinessNet#2]
Zdravo.

Najin projekt je končan. Bi ga lahko prosim pregledali?

Hvala in lep pozdrav.

**Comment by jaanos** [comment]
Imam nekaj komentarjev:
* Tabela `projekt` nima nastavljenega glavnega ključa - to naj bo seveda `id`.
* V tabeli `delavci` naj bo `projekt_id` referenca na tabelo `projekt`. Števca tukaj odstranita, saj nista potrebna.
* V tabeli `sporocila` naj bo glavni ključ samo `id`.
* Svetujem, da v aplikaciji ne uporabita `ISOLATION_LEVEL_AUTOCOMMIT`, pač pa na koncu vsakega zahtevka, kjer spreminjata podatke v bazi, pokličeta `baza.commit()` (tako ne bo prišlo do delnih vnosov podatkov ob napakah).
* Pri vpisu novega uporabnika je geslo pri vnosu vidno (v obeh poljih).
* Če EMŠO ne obstaja, pride do napake - lahko bi se izpisalo uporabniku bolj prijazno sporočilo.
* Pri seznamu projektov bi se lahko izpisal seznam sodelavcev (in ustrezno priredil seznam potencialnih sodelavcev za dodajanje).
* Manjka možnost urejanja projektov (vsaj spreminjanje stanja dokončanosti in porabe bi bilo smiselno).
* Pri dodajanju projekta za izbiro datuma uporabita ustrezni izbirnik datuma (lahko poiščeta kakega na internetu).
* Stolpec `narejeno` v tabeli `projekt` je tipa `integer`, a se v vnosnem obrazcu lahko vrednosti s klikom na puščice vrednost spreminja s korakom 0.01, kar lahko povzroči napako.
* Če želita dobiti ID nove vrstice, lahko uporabita `RETURNING`, npr.
```SQL
INSERT INTO projekt (ime, datum_zacetka, datum_konca, status, budget, porabljeno, narejeno, vsebina)
VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
RETURNING id
```
Potem lahko ID prebereta s `fetchone`:
```python
max_id, = c.fetchone()
```
* Dodajanje projekta ne deluje zaradi sledečega:
https://github.com/tinarazic/BusinessNet/blob/5491f5159e4ce1c9c18d71ea0dc3c2f2c517633a/Aplikacija/businessNet.py#L342-L343

**Comment by anamariostarijas** [comment]
Komentarje sva upoštevali in popravili napake. 

Imam še eno vprašanje. Pri nekaterih poizvedbah je bilo treba na precej grd način pretvoriti iz tuple v list. Če sem želela direktno, npr. `zeljen_seznam = list(c)`, je vračal elemente:
`('direktor',)`, želela bi pa imeti `direktor`. 
Kako bi lahko to popravila?

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij predmeta, tako da se lahko z @alenFMF domenita za termin zagovora, če se seveda še nista. Če bosta do takrat še kaj spreminjali, mi javita, da posodobim povezavo.

Če imata nabor (tuple) z enim elementom (oz. enojico), ga lahko prebereta v spremenljivko tako, da na levi strani enačaja spremenljivko podasta v enojici, npr.
```python
direktor, = ('direktor', ) # spremenljivka direktor dobi vrednost 'direktor'
```
Podobno lahko naredita tudi v zanki - npr. če naredita poizvedbo z enim samim stolpcem, lahko gresta čez vrednosti npr. tako:
```python
vrednosti = [x for x, in c]
# ali
for x, in c:
    ...
```

Še dve opombi:
* Na prvi strani je grafični prikaz napredka pri vseh projektih enak.
* `baza.commit()` uporabita samo enkrat za zahtevek:
https://github.com/tinarazic/BusinessNet/blob/8cd5beb972f93c918a3075c575b9d0123bbf5bfb/Aplikacija/businessNet.py#L347-L360
Tukaj torej naredita `baza.commit()` samo na koncu, pred `c.close()`. Če se torej npr. zalomi pri drugi poizvedbi, se bo tudi prva preklicala - tako v bazi ne bo projektov brez delavcev.

**Comment by tinarazic** [comment]
Zdravo, 

lahko prosim posodobite povezavo za jutrišnji zagovor pri profesorju.

**Comment by jaanos** [comment]
Sem posodobil.
